{{- if .Values.products.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: workhub
  labels:
    app: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      initContainers:
        - name: drizzle-migrate
          image: 570489932149.dkr.ecr.af-south-1.amazonaws.com/workhub/products:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - |
              cd apps/products && npx drizzle-kit migrate
          env:
            {{- include "common.env" . | nindent 12 }}
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@{{ .Release.Name }}-postgresql.postgresql.svc.cluster.local:5432/products
      containers:
        - name: products
          image: 570489932149.dkr.ecr.af-south-1.amazonaws.com/workhub/products:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              containerPort: 50051
          env:
            {{- include "common.env" . | nindent 12 }}
            - name: PORT
              value: "{{ .Values.products.port.http }}"
            - name: PRODUCTS_GRPC_SERVICE_URL
              value: "0.0.0.0:{{ .Values.products.port.grpc }}"
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@{{ .Release.Name }}-postgresql.postgresql.svc.cluster.local:5432/products
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /ready
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
